@echo off
echo Cleaning database...
del /f data\processed\aura.duckdb 2>nul

echo Running pipeline...
python scripts/run_pipeline.py

echo Checking timestamps...
python scripts/debug_timestamps.py

echo Running demo...
python scripts/demo_aura_queries.py
